### ISSUE TITLE
Sample FizzBuzz code in chapter 1 on the book "Introduction to Idris" never shows "Buzz"

### ISSUE THREAD

**Issue by tamy0612** [KeenS/zenn.dev#1]
At the line 42 in `what-is-idris.md`, `(_, 5)` never matches to the given tuple.
It should be `(_, 0)` I guess.

**Comment by KeenS** [comment]
（日本語の記事を管理するリポジトリなので日本語で対応します）
報告ありがとうございます。それに加えて実行結果のところも生成した実行ファイル名と実行しているファイル名が合っていないかったので修正します。
